# Generated by Django 5.1.3 on 2024-12-05 01:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='entry_period',
            field=models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator(message="O formato deve ser 'NNNN.N', onde N é um número e o dígito após o ponto deve ser 1 ou 2.", regex='^\\d{4}\\.[12]$')]),
        ),
    ]
