# Generated by Django 5.1.3 on 2024-12-09 23:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_entry_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='entry_period',
            field=models.CharField(default='2021.1', max_length=6, validators=[django.core.validators.RegexValidator(message="O formato deve ser 'NNNN.N', onde N é um número e o dígito após o ponto deve ser 1 ou 2.", regex='^\\d{4}\\.[12]$')]),
            preserve_default=False,
        ),
    ]
