# Generated by Django 5.1.3 on 2024-12-05 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
        ('subject', '0002_alter_subject_prerequisites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='subjects',
        ),
        migrations.AddField(
            model_name='schedule',
            name='subjects',
            field=models.ManyToManyField(related_name='schedules', to='subject.subject'),
        ),
    ]
