# Generated by Django 5.1.3 on 2024-12-04 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject_directory', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='directoryfile',
            unique_together={('name', 'directory')},
        ),
    ]
